### PR TITLE
Merge pull-ws-server into this project

### PR DESCRIPTION
**Pull request by dominictarr**
this PR combines pull-ws-server into this project.
this is a more convienent interface because you do not need to construct your own WebSocket object and then wrap it.

it also means we get more test coverage.

Though, the test coverage is also the awkward part of this PR. To get it to work nicely,
changed how the tests run, instead of having several files that combine together, I made each file start it's own server and then run it. That means it's not easy to run the tests in the brower (but it's never _easy_ to run the tests in the browser... we could run the tests in electron though?)

This also incorperates a change to source.js, to take a callback - when creating a outgoing client duplex pull-stream it's best to use a async function that callsback the stream (instead of a sync function that returns a stream)

If the stream cannot be created, the error will be handed to the stream creator, but if it was sync,
the stream it self errors - giving the error to a part of the application that probably doesn't know what to do with that. (and would thus have to pass it back to the stream creating code...)

This is the pattern I've settled on for creating client streams, as with tcp etc. and also usable with [pull-reconnect](https://github.com/dominictarr/pull-reconnect)

### CODE REVIEW

**Comment by dominictarr** [comment]
oh yeah, this merges BOTH histories together... I suggest we do a new major version

**Comment by DamonOehlman** [comment]
@dominictarr wowsers - nice one man :)

I'll merge this and then transfer it into the `pull-stream` org and let you take it from there.  I definitely agree on bumping major version.

I'm definitely interested in exploring using electron for testing - not something I've tried before but I can imagine that would be very useful.

**Comment by ahdinosaur** [comment]
hey this is cool! btw, y'all might be interested in [`tape-run`](https://github.com/juliangruber/tape-run).

**Comment by DamonOehlman** [comment]
Thanks @ahdinosaur - looks like I might have to buy @juliangruber a beer next time I see him :)

**Pull request merged**
